export const NamedPlatform = {
    "mame": "Multiple Arcade Machine Emulator",
    "fbneo": "FinalBurn Neo",
    "fba": "FinalBurn Neo",
    "daphne": "DAPHNE",
    "model3": "Sega Model 3",
    "naomi": "Sega NAOMI",
    "atomiswave": "Sammy Atomiswave",
    "channelf": "Fairchild Channel F",
    "atari2600": "Atari 2600",
    "o2em": "Magnavox Odyssey 2",
    "intellivision": "Intellivision",
    "atari5200": "Atari 5200",
    "colecovision": "ColecoVision",
    "vectrex": "Vectrex",
    "nes": "Nintendo Entertainment System",
    "nintendo": "Nintendo Entertainment System",
    "sg1000": "Sega SG-1000",
    "mastersystem": "Sega Master System",
    "fds": "Family Computer Disk System",
    "atari7800": "Atari 7800",
    "pcengine": "TurboGrafx-16 / PC Engine",
    "megadrive": "Sega Genesis / Mega Drive",
    "pcenginecd": "TurboGrafx-CD / PC Engine CD",
    "supergrafx": "PC Engine SuperGrafx",
    "snes": "Super Nintendo Entertainment System",
    "neogeo": "Neo Geo",
    "amigacdtv": "Commodore CDTV",
    "gx4000": "Amstrad GX4000",
    "segacd": "Sega CD / Mega CD",
    "snes-msu1": "Super NES CD-ROM",
    "jaguar": "Atari Jaguar",
    "3do": "3DO Interactive Multiplayer",
    "amigacd32": "Amiga CD32",
    "sega32x": "Sega 32X",
    "32x": "Sega 32X",
    "psx": "Sony PlayStation",
    "pcfx": "PC-FX",
    "neogeocd": "Neo Geo CD",
    "saturn": "Sega Saturn",
    "virtualboy": "Virtual Boy",
    "satellaview": "Satellaview",
    "sufami": "SuFami Turbo",
    "n64": "Nintendo 64",
    "dreamcast": "Sega Dreamcast",
    "n64dd": "Nintendo 64DD",
    "ps2": "Sony PlayStation 2",
    "gamecube": "Nintendo GameCube",
    "xbox": "Microsoft Xbox",
    "wii": "Nintendo Wii",
    "ps3": "Sony PlayStation 3",
    "wiiu": "Nintendo Wii U",
    "pico8": "PICO-8 fantasy console",
    "tic80": "TIC-80 fantasy console",
    "gameandwatch": "Game & Watch",
    "gb": "Game Boy",
    "gb2players": "Game Boy 2 Players",
    "lynx": "Atari Lynx",
    "gamegear": "Game Gear",
    "supervision": "Watara Supervision",
    "openbor": "OpenBor",
    "gbc": "Game Boy Color",
    "gbc2players": "Game Boy Color 2 Players",
    "ngp": "Neo Geo Pocket",
    "ngpc": "Neo Geo Pocket Color",
    "wswan": "WonderSwan",
    "wswanc": "WonderSwan Color",
    "gba": "Game Boy Advance",
    "pokemini": "Pokémon Mini",
    "nds": "Nintendo DS",
    "psp": "PlayStation Portable",
    "3ds": "Nintendo 3DS",
    "apple2": "Apple II",
    "pet": "Commodore PET",
    "atari800": "Atari 800",
    "c20": "Commodore VIC-20",
    "pc88": "NEC PC-8800",
    "zx81": "Sinclair ZX81",
    "x1": "Sharp X1",
    "zxspectrum": "Sinclair ZX Spectrum",
    "c64": "Commodore 64",
    "pc98": "NEC PC-9800",
    "msx1": "Microsoft MSX1",
    "amstradcpc": "Amstrad CPC",
    "thomson": "Thomson MO/TO Series Computer",
    "cplus4": "Commodore Plus/4",
    "atarist": "Atari ST",
    "msx2": "Microsoft MSX2",
    "c128": "Commodore 128",
    "apple2gs": "Apple IIGS",
    "amiga500": "Amiga 500",
    "x68000": "Sharp X68000",
    "msx2+": "Microsoft MSX2plus",
    "fmtowns": "FM Towns",
    "amiga1200": "Amiga 1200",
    "msxturbor": "Microsoft MSX turboR"
}

